### ISSUE TITLE
Export do PDF

### ISSUE THREAD

**Issue by jnv** [czechitas/tvorim-web-1#5]

**Comment by benabraham** [comment]
Na to jsou dvě řešení: dá se napsat návod, jak se to dělá (ručně několik kroků) a nebo upravit zdrojáky prezentace, aby to fungovalo o dost jednodušeji, což bude víc práce.

**Comment by jnv** [comment]
Ručně to řešíš jak?

**Comment by benabraham** [comment]
1. Reveal.js má verzi pro tisk na adresa?print-pdf vypadá to rozbitě, ale v samotným tisku to je ok.
2. Bohužel moje custom css/theme/czechitas.css s tím moc nepočítá a tak se nedá pro tisk použít a šlo by samozřejmě upravit. Proto pro tisk platí instrukce z v hlavičce index.html. Čímž se aplikuje standardní téma, který je černý text na bílým pozadí a s tiskem počítá.
```
 		<!-- pro tisk zakomentuj predchozi radek a odkomentuj nasledujici -->
		<!--<link rel="stylesheet" href="css/theme/white.css">-->
```
3. Ještě je dobrý v index.html odkomentovat jinej rozměr "stránky"
```
				// Uncomment for printing
				// width: 297*5, height: 210*5,
```
4. Ještě je potřeba zapnout viditelné poznámky (ano, počítá to s tím, že v poznámkách je konzistentní text, co dává smysl sám o sobě a aby ty slajdy taky k něčemu byly.
```
//				showNotes: true,    // zapnout viditelné poznámky
```
5. Zakomentovat všechny `<section data-markdown="slides/todolist.md" …,`, který nemaj jako materiál pro připomenutí toho, co se na workshopu dělalo, smysl.

A to je asi všechno, pokud jsem na něco nezapomněl. Vlastně zbývá v prohlížeči vytisknout do PDF.

Tu alternativu snadnou si představuju tak, že všechny tyhle kroky se stanou na základě toho přidání ?print-pdf (třeba že slajdy budou mít nějakej příznak toho, co se má tisknout a co ne). Případně že to vlastní css bude s tiskem počítat.

**Comment by jnv** [comment]
Vyřešeno v #11
